<?php
/**
 * This file is automatically generated by the wp_install.sh
 *
 * @file Config.php
 */

Namespace Base;

class Config {

	public function __construct(){
		# For our purposes, the theme name is the folder name that holds the WP theme.
		$this->theme_name = ( basename( dirname( dirname( __FILE__ ) ) ) );

		# Declare possible variable defaults.
		$this->has_blog = false;
		$this->has_ecommerce = false;
		$this->has_news_feed = false;
		$this->has_search = true;
		$this->has_image_slider = true;
		$this->has_ie8_support=true;
		$this->is_template_debug = true;
		$this->has_breadcrumbs=false;

		# REPLACE: CONFIGVARS
	}
}
